Improvements to app docs, updates app package version number and name
Esri/maps-app-javascript pull request #14
Opened 2020-07-22 19:36 UTC by esreli

This PR:

- introduces a TOC to (2) README files. The TOC was generated using MDTOC. 
- increments app version patch number
- describes doc changes in RELEASE
- renames `docs/index.md` to `docs/README.md`

@odoe i'm additionally requesting your review to ensure i've properly updated the app package version number and app package name. 

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2020-07-22 20:12 UTC, odoe approved these changes
Looks great, thanks!

2020-07-29 16:37 UTC, mikewilburn requested changes
I only caught one change, otherwise things look good here.

2020-07-29 16:37 UTC, mikewilburn commented on README.md
> +Generation a table of contents in this repository was performed using the [MDTOC package for Atom](https://atom.io/packages/atom-mdtoc).
I tend to prefer the original wording since it clarifies where these TOCs can be found:

```suggestion
Generation of this and other documents' table of contents in this repository was performed using the [MDTOC package for Atom](https://atom.io/packages/atom-mdtoc).
```

or if we want to simplify it:

```suggestion
Generating table of contents for documents in this repository was performed using the [MDTOC package for Atom](https://atom.io/packages/atom-mdtoc).
```

2020-07-30 20:19 UTC, mikewilburn approved these changes
I'm developing a preference for this wording now too. Looks good to me.

2020-07-31 16:05 UTC, merged